server:
  port: 9522

spring:
  main:
    allow-bean-definition-overriding: true
#mail:
#  host: ${MAIL_HOST}
#  port: ${MAIL_PORT}
#  protocol: ${MAIL_PROTOCOL}
#  smtp:
#    starttls:
#      enable: ${MAIL_STARTTLS}
